### ISSUE TITLE
Change the Room Creation Flow

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/viral-spiral-backend#43]
We want to reduce the friction in creating and joining rooms.

Adhiraj suggested this flow : 

1. Player visits viralspiral.net
2. Player enters the player count and clicks on "Create Room"
3. Player gets a link that they can share with others.
4. Player can click on the "join room" button next to the link to join the room themself

When the other Players click on the link, they just have to enter their chosen name.

As and when players are joining the room, the other players see a notification that "Player X has joined the room"

When everyone has joined the room, they see a notification that "The Game has started"

At this point the first card shows on the current player's screen.

### Doubts : 
While it might be acceptable to use just a randomly generated ID as the identifier for a room during the playtest sessions, how abuse proof is that in a production setting. Adhiraj mentioned that a lot of online multiplayer games are done this way. How do they prevent abuse? are they just banking on the fact that no one is trying to hack their way through to other people's room?
I think that generating human friendly room names and short numeric codes as password might be safer? so for instance i could say join the "happy panda" room with 5392 as the code. Should be less abuse prone?

**Comment by dennyabrain** [comment]
I had kept deprioritizing this as an issue wrt the playtests but after having conducted many mock sessions, i feel like this room creating and joining workflow is the first impression of the game that the players have and it can often get frustrating because of the number of things that can go wrong in the current implementation. So i'm bumping the priority of this for the playtests

**Comment by RishavT** [comment]
- [x] Use player count instead of list of player names while creating a game
- [ ] TODO @dennyabrain share link to join game - I feel this is better handled on the frontend. You can just tie a url parameter (like `?game=mygamename` - and have that linked to the game name field
- [x] For join room, the user can provide any name - and a new user will get created and assigned that name, which gets tied to that user henceforth.
- [x] Randomly generate game name of the format - user friendly text + random number
- [ ] Game has started event - pending, will do this as a part of the improvement to the about game signal.
